package com.shop.seckill.dao;

import com.shop.seckill.pojo.Item;

import java.util.List;

public interface ItemMapper {

    List<Item> listItem();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 23 13:26:36 CST 2022
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 23 13:26:36 CST 2022
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 23 13:26:36 CST 2022
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 23 13:26:36 CST 2022
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 23 13:26:36 CST 2022
     */
    int updateByPrimaryKey(Item record);

    int increaseSales(Integer id, Integer amount);

}