package com.shop.seckill.dao;

import com.shop.seckill.pojo.StockLog;

public interface StockLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Apr 26 16:39:09 CST 2022
     */
    int insert(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Apr 26 16:39:09 CST 2022
     */
    int insertSelective(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Apr 26 16:39:09 CST 2022
     */
    StockLog selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Apr 26 16:39:09 CST 2022
     */
    int updateByPrimaryKeySelective(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Apr 26 16:39:09 CST 2022
     */
    int updateByPrimaryKey(StockLog record);
}