package com.shop.seckill.dao;

import com.shop.seckill.pojo.UserPassword;

public interface UserPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 22 21:15:01 CST 2022
     */
    int insert(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 22 21:15:01 CST 2022
     */
    int insertSelective(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 22 21:15:01 CST 2022
     */
    UserPassword selectByPrimaryKey(Integer id);

    UserPassword selectByUserId(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 22 21:15:01 CST 2022
     */
    int updateByPrimaryKeySelective(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 22 21:15:01 CST 2022
     */
    int updateByPrimaryKey(UserPassword record);
}